attempting to get git hooks working properly

diff --git a/Makefile.d/scripts/hooks/pre-push b/Makefile.d/scripts/hooks/pre-push
--- a/Makefile.d/scripts/hooks/pre-push
+++ b/Makefile.d/scripts/hooks/pre-push
@@ -3,10 +3,14 @@
 remote="$1"
 url="$2"
 
+
+
 echo "\033[34m>starting $0\033[0m"
-make security || {
-  echo "\033[31m>Lint/security check failed $0\033[0m"
+
+make test || {
+  echo "\033[31m>test failed $0\033[0m"
   exit 1
 }
+
 echo "\033[32m>ok $0\033[0m"
 exit 0
