debugging staticcheck in github actions

diff --git a/.github/workflows/main-branch.yaml b/.github/workflows/main-branch.yaml
--- a/.github/workflows/main-branch.yaml
+++ b/.github/workflows/main-branch.yaml
@@ -43,7 +43,10 @@ jobs:
         shell: bash
         run: |
           make lint/install/staticcheck
-          command -v staticcheck || echo 'install failed.'
+          command -v staticcheck || {
+            echo 'install failed.'
+            exit 1
+          }
 
 #      - name: Run linter ${{ matrix.go-version }}
 #        shell: bash
