debugging staticcheck in github actions

diff --git a/.github/workflows/main-branch.yaml b/.github/workflows/main-branch.yaml
--- a/.github/workflows/main-branch.yaml
+++ b/.github/workflows/main-branch.yaml
@@ -35,24 +35,17 @@ jobs:
         with:
           go-version: ${{ matrix.go-version }}
 
-      - name: install staticcheck
+      - name: go mod tidy
         shell: bash
-        run: make lint/install/staticcheck
+        run: go mod tidy
 
-      - name: Print Go paths
+      - name: go mod tidy
         shell: bash
         run: |
-          echo "GOPATH: $(go env GOPATH)"
-          echo "list GOPATH"
-          ls -la $(go env GOPATH)
-          echo "list GOPATH/bin"
-          ls -la $(go env GOPATH)/bin
-          echo "list GOPATH/bin/"
-          ls -la $(go env GOPATH)/bin/
-          echo "find staticcheck"
-          command -v staticcheck
+          make lint/install/staticcheck
+          command -v staticcheck || echo 'install failed.'
 
-      - name: Run linter ${{ matrix.go-version }}
-        shell: bash
-        run: |
-          PATH=$(go env GOPATH):${PATH} make security
+#      - name: Run linter ${{ matrix.go-version }}
+#        shell: bash
+#        run: |
+#          PATH=$(go env GOPATH):${PATH} make security
